import { Navbar } from "./components/Navbar";
import ThemeRegistry from './components/ThemeRegistry/ThemeRegistry';
import './globals.css';
import type { Metadata } from 'next';
//import { Roboto } from 'next/font/google';

//const roboto = Roboto({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tracking',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Navbar /> 
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
